// vite-react/src/App.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
// import { useState, useEffect, useRef } from 'react'
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import '../../wcs/esmodule.js'



function App() {
  const [count, setCount] = useState(0)
  // const el = useRef()

  // useEffect(()=>{
  //  el.current && el.current.addEventListener('changeEvent', (e: any)=>{
  //   console.log(222, e)
  //  })
  // }, [])

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
      {/* <components-div></components-div> */}
      {/* <cl-input  placeholder="欢迎使用web输入组件" value={'666'} ref={el}></cl-input> */}
    </>
  )
}

export default App

// vite-vue/src/App.vue
<script setup>
import HelloWorld from './components/HelloWorld.vue'
import '../../wcs/esmodule'
import { ref, onMounted } from 'vue'

const hello = ref(null);
onMounted(() => {
  hello.value.addEventListener('changeEvent', (e)=>{
    console.log(222, e)
   })
})

</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
  <components-div></components-div>

  <cl-input
    placeholder="欢迎使用web输入组件"
    ref="hello"
  ></cl-input>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
